name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  markdown:
    name: 📝 Markdown Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: '**/*.md'
          config: 'config/custom.markdownlint.jsonc'
  spelling:
    name: ✍️ Spelling Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Spell Check Code
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: '**/*.md'
          config: 'config/cspell.json'
  structure:
    name: 📂 Structure Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for Large Files
        run: bash ./scripts/check_large_files.sh